services:

  - type: web

    name: deepfake-detection-api

    env: python

    plan: free

    buildCommand: pip install -r backend/requirements.txt

    startCommand: bash backend/start.sh

    envVars:

      - key: PYTHON_VERSION

        value: 3.10.12

    autoDeploy: true
